CC = gcc
CFLAGS = -Wall -Wextra

all: binary_tree_program

binary_tree_program: main.o binary_tree.o pilha.o
	$(CC) $(CFLAGS) -o binary_tree_program main.o binary_tree.o pilha.o

main.o: main.c binary_tree.h pilha.h
	$(CC) $(CFLAGS) -c -o main.o main.c

binary_tree.o: binary_tree.c binary_tree.h pilha.h
	$(CC) $(CFLAGS) -c -o binary_tree.o binary_tree.c

pilha.o: pilha.c pilha.h
	$(CC) $(CFLAGS) -c -o pilha.o pilha.c

clean:
	rm -f binary_tree_program main.o binary_tree.o pilha.o
